version: '3.8'

services:
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - fraud-detection-network
    volumes:
      - ./ml-service:/app
      - ./data:/app/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - ml-service
    networks:
      - fraud-detection-network
    volumes:
      - ./backend:/app
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/fraud_detection
      - ML_SERVICE_URL=http://ml-service:8000
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fraud-detection-network
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_WS_URL=http://localhost:3001

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - fraud-detection-network
    volumes:
      - mongodb-data:/data/db

networks:
  fraud-detection-network:
    driver: bridge

volumes:
  mongodb-data: